global au.edu.swin.ict.road.composite.regulation.passthrough.PassthroughActions actions;
import au.edu.swin.ict.road.composite.rules.events.contract.MessageReceivedEvent;
rule "sendGCLocation"
    when
		$msg : MessageReceivedEvent(operationName == "sendGCLocation", response==false)
    then
		actions.publishEvent("eGC1LocKnown",$msg);
		actions.publishEvent("eRepairAcceptByGC1",$msg);
end

rule "sendGCLocationResponse"
    when
		$msg : MessageReceivedEvent(operationName == "sendGCLocation", response==true)
    then
		actions.publishEvent("eDeliveredVehicleToGC1ByTC1",$msg);
end