global au.edu.swin.ict.road.composite.regulation.synchronization.SynchronizationActions actions;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.EventRecord;
import au.edu.swin.ict.road.common.VSNInstance;
import au.edu.swin.ict.road.composite.message.MessageWrapper;

rule "orderRepair"
  when
   $e1 : EventRecord(eventId == "eRepairReqdFromGC2BySC")
  then
   disabledSet.disable("orderRepair");
   MessageWrapper [] msgs = actions.Pull(new String []{"SC-GC2.orderRepair.Req"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"OrderRepairGC2.xsl","OrderRepair");
   actions.ExecuteTask(exMsg);
end

rule "orderRepairFromMM"
  when
  ( $e1 : EventRecord(eventId == "eRepairReqdFromGC2ByMM") ) and  ( $vsnIns : VSNInstance(state == "active"))
  then
   disabledSet.disable("orderRepairFromMM");
   MessageWrapper [] msgs = actions.Pull(new String []{"MM-GC2.orderRepair.Req"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"OrderRepairFromGC2ByMM.xsl","OrderRepair");
   actions.ExecuteTask(exMsg);
end

rule "assessRepairTC1"
  when
   $e1 : EventRecord(eventId == "eDeliveredVehicleToGC2ByTC1")
  then
   disabledSet.disable("assessRepairTC1");
   MessageWrapper [] msgs = actions.Pull(new String []{"GC2-TC1.sendGCLocation.Res"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"AssessRepairTC1.xsl","AssessRepair");
   actions.ExecuteTask(exMsg);
end

rule "assessRepairTC2"
  when
   $e1 : EventRecord(eventId == "eDeliveredVehicleToGC2ByTC2")
  then
   disabledSet.disable("assessRepairTC2");
   MessageWrapper [] msgs = actions.Pull(new String []{"GC2-TC2.sendGCLocation.Res"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"AssessRepairTC2.xsl","AssessRepair");
   actions.ExecuteTask(exMsg);
end

rule "doRepair"
  when
   $e1 : EventRecord(eventId == "eReceivedParts")
  then
   disabledSet.disable("doRepair");
   MessageWrapper [] msgs = actions.Pull(new String []{"GC2-PS.orderParts.Res"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"DoRepairGC2.xsl","DoRepair");
   actions.ExecuteTask(exMsg);
end