global au.edu.swin.ict.road.composite.regulation.routing.RoutingActions actions;
import au.edu.swin.ict.road.composite.rules.events.composite.RoleServiceMessage;
rule "assessRepairResponse"
  when
   $msg : RoleServiceMessage(operationName== "assessRepairResponse", state=="forwardable")
  then
   actions.Forward("GC1-AS.orderRepairAssessment.Res","OrderRepairAssessmentRes.xsl",$msg);
   actions.Forward("AS-SC.payRepairAssessment.Req","PayRepairAssessmentReq.xsl",$msg);
end