global au.edu.swin.ict.road.composite.regulation.synchronization.SynchronizationActions actions;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.EventRecord;
import au.edu.swin.ict.road.composite.message.MessageWrapper;
rule "assessRepair"
  when
   $e1 : EventRecord(eventId == "eRepairAssessmentReq")
  then
   disabledSet.disable("assessRepair");
   MessageWrapper [] msgs = actions.Pull(new String []{"GC1-AS.orderRepairAssessment.Req"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"OrderRepairAssessment.xsl","AssessRepair");
   actions.ExecuteTask(exMsg);
end