global au.edu.swin.ict.road.composite.regulation.routing.RoutingActions actions;
import au.edu.swin.ict.road.composite.rules.events.composite.RoleServiceMessage;
rule "rentRoomResponse"
  when
   $msg : RoleServiceMessage(operationName== "rentRoomResponse", state=="forwardable")
  then
   actions.Forward("SC-HC.rentRoom.Res","RentRoomRes.xsl",$msg);
end
rule "endRoomRentResponse"
  when
   $msg : RoleServiceMessage(operationName== "endRoomRentResponse", state=="forwardable")
  then
   actions.Forward("SC-HC.endRoomRent.Res","EndRoomRentRes.xsl",$msg);
   actions.Forward("SC-HC.payRoomRent.Req","PayRoomRentReq.xsl",$msg);
end