global au.edu.swin.ict.road.composite.regulation.routing.RoutingActions actions;
import au.edu.swin.ict.road.composite.rules.events.composite.RoleServiceMessage;
rule "inspectAccidentResponse"
  when
   $msg : RoleServiceMessage(operationName== "inspectAccidentResponse", state=="forwardable")
  then
   actions.Forward("LF-TC2.authorizeTow.Req","AuthorizeTowFromLFToTC2.xsl",$msg);
   actions.Forward("SC-LF.payLegalAid.Req","PayLegalAidFromLFToSC.xsl",$msg);
end