global au.edu.swin.ict.road.composite.regulation.synchronization.SynchronizationActions actions;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.EventRecord;
import au.edu.swin.ict.road.composite.message.MessageWrapper;
rule "inspectAccident"
  when
   $e1 : EventRecord(eventId == "eInspectAccidentReqd")
  then
   disabledSet.disable("inspectAccident");
   MessageWrapper [] msgs = actions.Pull(new String []{"SC-LF.inspectAccident.Req"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"InspectAccident.xsl","InspectAccident");
   actions.ExecuteTask(exMsg);
end