global au.edu.swin.ict.road.composite.regulation.passthrough.PassthroughActions actions;
import au.edu.swin.ict.road.composite.rules.events.contract.MessageReceivedEvent;
rule "reimburse"
    when
		$msg : MessageReceivedEvent(operationName == "reimburse",  response ==false)
    then
		actions.publishEvent("eReimburseReqd",$msg);
end
rule "reimburseResponse"
    when
		$msg : MessageReceivedEvent(operationName == "reimburse",  response ==true)
    then
		actions.publishEvent("eReimbursed",$msg);
end