global au.edu.swin.ict.road.composite.regulation.routing.RoutingActions actions;
import au.edu.swin.ict.road.composite.rules.events.composite.RoleServiceMessage;
rule "orderPartsResponse"
  when
   $msg : RoleServiceMessage(operationName== "orderPartsResponse", state=="forwardable")
  then
   actions.Forward("GC1-PS.orderParts.Res","OrderPartsRes.xsl",$msg);
   actions.Forward("PS-SC.payParts.Req","PayPartsReq.xsl",$msg);
end