global au.edu.swin.ict.road.composite.regulation.routing.RoutingActions actions;
import au.edu.swin.ict.road.composite.rules.events.composite.RoleServiceMessage;
rule "orderTaxiResponse"
  when
   $msg : RoleServiceMessage(operationName== "orderTaxiResponse", state=="forwardable")
  then
   actions.Forward("SC-TX.sendTaxiInvoice.Req","SendTaxiInvoiceReq.xsl",$msg);
   actions.Forward("TX-MM.notifyTaxiBooking.Req","NotifyTaxiBookingReq.xsl",$msg);
end