global au.edu.swin.ict.road.composite.regulation.synchronization.SynchronizationActions actions;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.EventRecord;
import au.edu.swin.ict.road.composite.message.MessageWrapper;

rule "rentBike"
  when
   ($e1 : EventRecord(eventId == "eRentBike")) and ($e2 : EventRecord(eventId == "eSendBikeRequirements"))
  then
   disabledSet.disable("rentBike");
   MessageWrapper [] msgs = actions.Pull(new String []{"SC-BR.rentBike.Req","CM-BR.sendBikeRequirements.Req"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"RentBike.xsl","RentBike");
   actions.ExecuteTask(exMsg);
end