global au.edu.swin.ict.road.composite.regulation.passthrough.PassthroughActions actions;
import au.edu.swin.ict.road.composite.rules.events.contract.MessageReceivedEvent;
rule "sendTourRequirements"
    when
		$msg : MessageReceivedEvent(operationName == "sendTourRequirements",  response ==false)
    then
		actions.publishEvent("eSendTourRequirementsToTC",$msg);
end
rule "sendTourReservation"
    when
		$msg : MessageReceivedEvent(operationName == "sendTourReservation",  response ==false)
    then
		actions.publishEvent("eSendTourReservationToCM",$msg);
end