global au.edu.swin.ict.road.composite.regulation.synchronization.SynchronizationActions actions;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.EventRecord;
import au.edu.swin.ict.road.composite.message.MessageWrapper;

rule "rentEquipment"
  when
   ($e1 : EventRecord(eventId == "eRentEquipmentByEP1")) and   ($e2 : EventRecord(eventId == "eSendEquipmentRequirementsToEP1"))
  then
   disabledSet.disable("rentEquipment");
   MessageWrapper [] msgs = actions.Pull(new String []{"SC-EP1.rentEquipment.Req","CM-EP1.sendEquipmentRequirements.Req"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"RentEquipment.xsl","RentEquipment");
   actions.ExecuteTask(exMsg);
end