global au.edu.swin.ict.road.composite.regulation.routing.RoutingActions actions;
import au.edu.swin.ict.road.composite.rules.events.composite.RoleServiceMessage;

rule "findGuideResponse"
  when
   $msg : RoleServiceMessage(operationName== "findGuideResponse", state=="forwardable")
  then
   actions.Forward("SC-TG.findGuide.Res","FindGuideRes.xsl",$msg);
end

rule "bookGuideResponse"
  when
   $msg : RoleServiceMessage(operationName== "bookGuideResponse", state=="forwardable")
  then
   actions.Forward("SC-TG.bookGuide.Res","BookGuideRes.xsl",$msg);
   actions.Forward("TG-VR.sendTourSchedule.Req","SendTourScheduleReq.xsl",$msg);
end