global au.edu.swin.ict.road.composite.regulation.synchronization.SynchronizationActions actions;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.EventRecord;
import au.edu.swin.ict.road.composite.message.MessageWrapper;

rule "findGuide"
  when
   $e1 : EventRecord(eventId == "eFindGuide")
  then
   disabledSet.disable("findGuide");
   MessageWrapper [] msgs = actions.Pull(new String []{"SC-TG.findGuide.Req"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"FindGuide.xsl","FindGuide");
   actions.ExecuteTask(exMsg);
end

rule "bookGuide"
  when
   $e1 : EventRecord(eventId == "eBookGuide")
  then
   disabledSet.disable("bookGuide");
   MessageWrapper [] msgs = actions.Pull(new String []{"SC-TG.bookGuide.Req"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"BookGuide.xsl","BookGuide");
   actions.ExecuteTask(exMsg);
end
