global au.edu.swin.ict.road.composite.regulation.routing.RoutingActions actions;
import au.edu.swin.ict.road.composite.rules.events.composite.RoleServiceMessage;

rule "bookTaxiResponse"
  when
   $msg : RoleServiceMessage(operationName== "bookTaxiResponse", state=="forwardable")
  then
   actions.Forward("SC-TX.bookTaxi.Res","BookTaxiRes.xsl",$msg);
   actions.Forward("CM-TX.sendTaxiReservation.Req","SendTaxiReservationReq.xsl",$msg);
end