global au.edu.swin.ict.road.composite.regulation.passthrough.PassthroughActions actions;
import au.edu.swin.ict.road.composite.rules.events.contract.MessageReceivedEvent;
rule "sendLocation"
    when
		$msg : MessageReceivedEvent(operationName == "sendLocation",  response ==false)
    then
		actions.publishEvent("eSendLocToTX",$msg);
end
rule "sendTaxiReservation"
    when
		$msg : MessageReceivedEvent(operationName == "sendTaxiReservation",  response ==false)
    then
		actions.publishEvent("eSendTaxiReservationToCM",$msg);
end