global au.edu.swin.ict.road.composite.regulation.synchronization.SynchronizationActions actions;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.EventRecord;
import au.edu.swin.ict.road.composite.message.MessageWrapper;

rule "rentAndDeliverEquipment"
  when
   ($e1 : EventRecord(eventId == "eSendEquipmentRequirementsToEP2")) and   ($e2 : EventRecord(eventId == "eRentAndDeliverEquipmentByEP2"))
  then
   disabledSet.disable("rentAndDeliverEquipment");
   MessageWrapper [] msgs = actions.Pull(new String []{"SC-EP2.rentAndDeliverEquipment.Req","CM-EP2.sendEquipmentRequirements.Req"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"RentAndDeliverEquipment.xsl","RentAndDeliverEquipment");
   actions.ExecuteTask(exMsg);
end