global au.edu.swin.ict.road.composite.regulation.synchronization.SynchronizationActions actions;
global au.edu.swin.ict.road.common.DisabledRuleSet disabledSet;
import au.edu.swin.ict.road.common.EventRecord;
import au.edu.swin.ict.road.composite.message.MessageWrapper;

rule "orderGrocery"
  when
   ($e1 : EventRecord(eventId == "eOrderGrocery")) and ($e2 : EventRecord(eventId == "eSendGroceryList"))
  then
   disabledSet.disable("orderGrocery");
   MessageWrapper [] msgs = actions.Pull(new String []{"CM-GR.sendGroceryList.Req","SC-GR.orderGrocery.Req"});
   MessageWrapper exMsg = actions.Synthesis(msgs,"OrderGrocery.xsl","OrderGrocery");
   actions.ExecuteTask(exMsg);
end