global au.edu.swin.ict.road.composite.regulation.passthrough.PassthroughActions actions;
import au.edu.swin.ict.road.composite.rules.events.contract.MessageReceivedEvent;
rule "orderGrocery"
    when
		$msg : MessageReceivedEvent(operationName == "orderGrocery",  response ==false)
    then
		actions.publishEvent("eOrderGrocery",$msg);
end
rule "orderGroceryResponse"
    when
		$msg : MessageReceivedEvent(operationName == "orderGrocery",  response ==true)
    then
		actions.publishEvent("eOrderedGrocery",$msg);
end