global au.edu.swin.ict.road.composite.regulation.passthrough.PassthroughActions actions;
import au.edu.swin.ict.road.composite.rules.events.contract.MessageReceivedEvent;
rule "bookTaxi"
    when
		$msg : MessageReceivedEvent(operationName == "bookTaxi",  response ==false)
    then
		actions.publishEvent("eBookTaxi",$msg);
end
rule "bookTaxiResponse"
    when
		$msg : MessageReceivedEvent(operationName == "bookTaxi",  response ==true)
    then
		actions.publishEvent("eReservedTaxi",$msg);
end